### ISSUE TITLE
Channel that doesn't remove the oldest messages when receiver buffer is full

### ISSUE THREAD

**Issue by ela-kotulska-frequenz** [frequenz-floss/frequenz-channels-python#73] opened 2023-02-17 08:29 UTC
### What's needed?

Now when receiver buffer size is full and new message comes, then the oldest message is removed.
But in some cases it is important that each request is received and processed.
One such use-case is when we request to subscribe for metric data.
If we have many components/metrics and we subscribe for all data at the startup, then default receiver buffer size is not enough. The oldest messages are removed and the application doesn't work properly because we don't receive data.

### Proposed solution

There are two possible solutions:
1. We could have special kind of blocking channel. 
If sender tries to send message, but the receiver buffer size is full, then we should block sender until the receiver buffer size has free space. For implementation simplicity it is enough if channel have many senders and only one receiver. (this covers our all current use-cases)

2. We could have option to dynamically increase the buffer size - but in that case there might be more and more requests, and receiver is unable to process them in time and the memory might increase too much. 

### Use cases

For now the only use-case was subscribing for the component metric data.

**Comment by leandro-lucarella-frequenz** [comment] 2023-02-17 11:14
Option 1 is #20, right?

Option 2 IMHO doesn't make a lot of sense, if you need a bigger buffer, just use a bigger buffer. If you mean an infinite buffer, I also don't think is a good idea.

**Comment by llucax** [comment] 2023-08-07 09:01
I will close this as a duplicate of #20 as I don't think option 2 is realistic.

**Closed as not planned by llucax** 2023-08-07 09:01 UTC
Labels: resolution:duplicate, type:enhancement, part:channels
